server:
  port: 8088 #端口号
spring:
  devtools:
    restart:
      enabled: false #热加载关闭开启控制
  datasource:
    name: shop #数据库名称
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
       #监控统计拦截的filters
      filters: stat
      driver-class-name: org.sqlite.JDBC
      #基本属性
      #打包环境
      #url: jdbc:sqlite::resource:db_generalaviation.db
      #开发环境
      url: jdbc:sqlite:D:/db_generalaviation.db
      username:
      password:
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #
      max-wait: 60000
      #间隔多久进行一次检测，检测需要获取连接等待超时时间关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: -1
      ## 该配置节点为独立的节点，如果把这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.syxy.generalaviation.entity  # 注意：对应实体类的路径（类别名）
  #开启驼峰，否则查询只要名称不对就是NULL
  configuration:
    map-underscore-to-camel-case: true
#pagehelper框架自带分页器配置
pagehelper:
  helperDialect: sqlite
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# 日志配置
logging:
  config: classpath:config/logger-config.xml